### ISSUE TITLE
Getting "Could not find class php::" when loading

### ISSUE THREAD

**Issue by nickygerritsen** [mattheath/puppet-php#9]
I get the following error:

``` bash
Error: Could not find class php:: for tandem-imac.local on node tandem-imac.local
```

With the following config:

``` ruby
  require php::5-4-10

  class { 'php::global':
    version => '5.4.10'
  }

  php::extension::apc { "apc for ${version}":
    php     => $version
  }

  include php::fpm::5-4-10
```

What am I doing wrong?

**Comment by mattheath** [comment]
@nickygerritsen have you defined `$version` ? If you haven't then it'll be null which explains the problem above.

You should change your APC definition from this

``` puppet
php::extension::apc { "apc for ${version}":
  php     => $version
}
```

to this:

``` puppet
php::extension::apc { "apc for 5.4.10":
  php     => '5.4.10'
}
```

Also you can remove `require php::5-4-10` as both your `php::global` and `php::fpm::5-4-10` will ensure that php 5.4.10 is installed.

Let me know how you get on! :smile:

**Comment by nickygerritsen** [comment]
This seems to work, but now it is giving this error:

``` bash
Notice: /Stage[main]/Php::5-4-10/Php::Version[5.4.10]/File[/opt/boxen/data/php/5.4.10/cache]/ensure: created
Already on 'master'
Switched to a new branch 'build'
Installing PHP 5.4.10, this may take a while...
export PHP_AUTOCONF=/opt/boxen/homebrew/bin/autoconf && cd /opt/boxen/phpenv/php-src/ && ./buildconf --force
Forcing buildconf
Removing configure caches
buildconf: checking installation...
buildconf: autoconf version 2.69 (ok)
rebuilding aclocal.m4
rebuilding configure
rebuilding main/php_config.h.in
Configuring PHP 5.4.10: --prefix=/opt/boxen/phpenv/versions/5.4.10 --localstatedir=/var --sysconfdir=/opt/boxen/config/php/5.4.10 --with-config-file-path=/opt/boxen/config/php/5.4.10 --with-config-file-scan-dir=/opt/boxen/config/php/5.4.10/conf.d --with-iconv-dir=/usr --enable-dba --with-ndbm=/usr --enable-exif --enable-soap --enable-wddx --enable-ftp --enable-sockets --enable-zip --enable-pcntl --enable-shmop --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-mbstring --enable-mbregex --enable-bcmath --enable-calendar --with-ldap --with-ldap-sasl=/usr --with-xmlrpc --with-kerberos=/usr --with-xsl=/usr --with-gd --enable-gd-native-ttf --with-freetype-dir=/opt/boxen/homebrew/opt/freetype --with-jpeg-dir=/opt/boxen/homebrew/opt/jpeg --with-png-dir=/opt/boxen/homebrew/opt/libpng --with-gettext=/opt/boxen/homebrew/opt/gettext --with-gmp=/opt/boxen/homebrew/opt/gmp --with-zlib=/opt/boxen/homebrew/opt/zlib --with-snmp=/usr --with-libedit --with-mhash --with-curl --with-openssl=/usr --with-bz2=/usr --with-mysql-sock=/tmp/mysql.sock --with-mysqli=mysqlnd --with-mysql=mysqlnd --with-pdo-mysql=mysqlnd --enable-fpm
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
configure: error: Cannot locate header file libintl.h
checking for grep that handles long lines and -e... /usr/bin/grep
[...]
If configure fails try --with-vpx-dir=<DIR>
checking for png_write_image in -lpng... yes
If configure fails try --with-xpm-dir=<DIR>
checking for FT_New_Face in -lfreetype... yes
checking for GNU gettext support... yes
make: *** No targets specified and no makefile found.  Stop.

make: Nothing to be done for `install'.
make: *** No rule to make target `clean'.  Stop.

chown: /opt/boxen/phpenv/versions/5.4.10: No such file or directory
```

It seems I'm missing libintl? Is that the problem why the makefile can not be found?

**Comment by mattheath** [comment]
From a cursory google search this looks related to gettext. Which version of the PHP module are you using?

Also, does `brew list` show gettext as installed?

**Comment by mattheath** [comment]
Just to confirm - I can reproduce this by removing the `pkgconfig` boxen module from my Puppetfile - it's a dependency since `0.3.5`.

If you bump your PHP module version to `0.3.7` and check that your Puppetfile contains the following lines (along with the other dependencies in the readme), this should fix the issue:

```
github "pkgconfig",  "1.0.0"
github "pcre",       "1.0.0"
```

**Comment by nickygerritsen** [comment]
OK what I have found out: if I start my boxen "from scratch" (i.e. rm -Rf /opt/boxen) then it does not work (with the above error).
However, when I first "boxen" everything except PHP and afterwards add php to site.pp it works ok.
So something seems to be wrong in the dependency-flow?

**Comment by mattheath** [comment]
Yeah it looks like the dependencies weren't in the correct order and some of the paths weren't fully qualified. Sorry about this, should have a fix this evening.

**Comment by mattheath** [comment]
I've bumped the module version to `0.3.8` which should fix the dependency ordering issues, and also making the paths for the executables used fully qualified. It's this part which explains the module working on the 2nd+ passes, but not the first. 

@nickygerritsen I've tested it several times from a clean install and it appars to work, could you let me know how you get on?

**Comment by nickygerritsen** [comment]
OK clean install works fine now. However there is still a problem:
When I run "boxen" again (even without changing anything) it tries to fetch "php-src" again and then errors because the directory already exists. I guess something goes wrong in marking "php-src" as installed?

**Comment by mattheath** [comment]
Fantastic. That's quite interesting as the `php-src` folder is defined by boxen's repository type rather than any custom code. Is there a `.git` folder present within `/opt/boxen/phpenv/php-src`? Could you paste some logs of the error?

**Comment by nickygerritsen** [comment]
No there is .git directory, but there is one a level higher:

``` bash
[12:38:10][nicky@Nickys-iMac.local:/opt/boxen/phpenv/php-src]$ ls -l .git
ls: .git: No such file or directory
[12:38:19][nicky@Nickys-iMac.local:/opt/boxen/phpenv/php-src]$ ls -l ../.git
total 48
-rw-r--r--   1 nicky  staff   211 20 mrt 08:46 FETCH_HEAD
-rw-r--r--   1 nicky  staff    23 20 mrt 08:46 HEAD
-rw-r--r--   1 nicky  staff   245 20 mrt 08:46 config
-rw-r--r--   1 nicky  staff    73 20 mrt 08:46 description
drwxr-xr-x  10 nicky  staff   340 20 mrt 08:46 hooks
-rw-r--r--   1 nicky  staff  6693 20 mrt 12:37 index
drwxr-xr-x   3 nicky  staff   102 20 mrt 08:46 info
drwxr-xr-x   4 nicky  staff   136 20 mrt 08:46 logs
drwxr-xr-x   4 nicky  staff   136 20 mrt 08:46 objects
drwxr-xr-x   5 nicky  staff   170 20 mrt 08:46 refs
[12:38:23][nicky@Nickys-iMac.local:/opt/boxen/phpenv/php-src]$ 
```

The log file can be found at: https://gist.github.com/nickygerritsen/5204036

**Comment by mattheath** [comment]
Ok these two lines are the important part:

```
Wed Mar 20 09:11:38 +0100 2013 Puppet (err): Execution of '/opt/boxen/homebrew/bin/git clone --recurse-submodules -c credential.helper=/opt/boxen/bin/boxen-git-credential https://github.com/php/php-src /opt/boxen/phpenv/php-src' returned 128: fatal: destination path '/opt/boxen/phpenv/php-src' already exists and is not an empty directory.
Wed Mar 20 09:11:38 +0100 2013 /Stage[main]/Php/Repository[/opt/boxen/phpenv/php-src]/ensure (err): change from absent to present failed: Execution of '/opt/boxen/homebrew/bin/git clone --recurse-submodules -c credential.helper=/opt/boxen/bin/boxen-git-credential https://github.com/php/php-src /opt/boxen/phpenv/php-src' returned 128: fatal: destination path '/opt/boxen/phpenv/php-src' already exists and is not an empty directory.
```

You seem to have something in the php-src folder, but not a git repository. I'm surprised it'll actually build PHP with this failing as the repository is a dependency of the `php::version` class. Deleting that folder should fix the problem, it'll then recreate it. I don't know how it got into that state though.

**Comment by nickygerritsen** [comment]
OK will try this tonight when I'm at my iMac.
The php-src directory does contain the PHP source files btw, but only not a git repository.

**Comment by mattheath** [comment]
Interesting, I think this must be from an earlier version of the module which phpenv/php-build cached the source code. php-build has been replaced now by custom providers and I thought this was a backwards compatible change with the correct tasks to clean anything up - will check this.

**Comment by nickygerritsen** [comment]
Indeed after removing the directory it seems to work. I have no clue how the .git directory was not there....

**Comment by mattheath** [comment]
Fantastic. Everything working correctly now?

**Comment by nickygerritsen** [comment]
Yep seems to have no problems anymore :)

**Comment by mattheath** [comment]
Great, will close this off. Thanks for testing! :+1:
